baseurl = "https://dacolloquium.com/"
languageCode = "en-us"
title = "Data Analytics Colloquium"
theme = "castanet"
googleAnalytics = ""
themesdir = "../.."
paginate = "9"


[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	seminar = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "/about"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact"

[[Menu.Main]]
    name = "Hosts"
    identifier = "hosts"
    url = "/host"

[[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "/guest"

[[Menu.Main]]
    name = "Resources"
    identifier = "resources"
    url = "#!"

# [[Menu.Main]]
#    name = "Books"
#    identifier = "books"
#    url = "/books"
#    parent = "resources"
[[Menu.Main]]
    name = "Register"
    identifier = "register"
    url = "/books"
    parent = "resources"

[params]
mainSections = ["seminar"]
site_theme = "blue"
site_layout = "grid"
# site_layout = "row"
enable_jumbo = "true"
# enable_jumbo = "false"
# truncate = "100"
# about_logo = "/img/hugocast.png"
copyright_notice = "Copyright 2020 [Data Analytics Colloquium](https://www.datacolloquium.com)"
# itunes_subscribe = "https://podcasts.apple.com/us/podcast/arrested-devops/id773888088?ign-mpt=uo%3D4&mt=2"
# android_subscribe = "http://subscribeonandroid.com/feeds.podtrac.com/VGAulpN7MY1U"
# spotify_subscribe = "https://open.spotify.com/show/..."
# google_play_subscribe = "https://goo.gl/app/playmusic?ibi=com.google.PlayMusic&isi=691797987&ius=googleplaymusic&link=https://play.google.com/music/m/Ihj4yege3lfmp3vs5yoopgxijpi?t%3DArrested_DevOps"
# stitcher_subscribe = "http://www.stitcher.com/podcast/arrested-devops-2/arrested-devops"
# soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
# pocketcasts_subscribe = "http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
# mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
# rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "Data Analytics Colloquium is a public forum featuring international top-notch data scientists and latest cutting data science projects.  Members of the colloquium will engage in conversation with speakers and replication of data methods introduced employing real data.  The colloquium will be delivered using online learning platform and repository system for code and data sharing.  The weekly webinars will be co-hosted by NCHU and UTD and participated by students in Taiwan and Texas with real time access and archived events will be free and available to the public.   Hosting faculty members in two universities will invite scholars from universities in each country to participate as discussants."
# media_prefix = ""
# disqusShortname = ""
#  [params.feed]
#    copyright = "Copyright 2020 Data Analytics Colloquium" #do not use markdown in this field; it is used in the feed
#    itunes_subtitle = "The public data science forum for social and policy sciences" #no markdown or HTML
#    itunes_author = "Karl Ho and CH Pan" #no markdown or HTML
#    itunes_summary = "Data Analytics Colloquium is a public forum featuring international top-notch data scientists and latest cutting data science projects.  Members of the colloquium will engage in conversation with speakers and replication of data methods introduced employing real data.  The colloquium will be delivered using online learning platform and repository system for code and data sharing.  The weekly webinars will be co-hosted by NCHU and UTD and participated by students in Taiwan and Texas with real time access and archived events will be free and available to the public.   Hosting faculty members in two universities will invite scholars from universities in each country to participate as discussants." # Limited to 4000 characters or less, plain text, no HTML
#    itunes_owner_name = "Karl Ho"
#    itunes_owner_email = "dacolloquium@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on Apple Podcasts. It will not be publicly displayed on Apple Podcasts.
#    itunes_image = "" #fqdn to the image art for your podcast
#    itunes_top_category = "Technology"
#    itunes_first_sub_category = "Software How-To"
#    itunes_second_sub_category = "Tech News"
#    language = "en-us"

  [params.realfavicongenerator] # https://realfavicongenerator.net/
    mask_icon_color="#5bbad5"
   msapplication_tilecolor="#2b5797"
    theme_color="#ffffff"

#  [params.podlove] # https://subscribe-button.podlove.org
#    subscribe_title = ""              # fallback: site title from above
#    subscribe_subtitle = ""           # fallback: ""
#    subscribe_description = ""        # fallback: ""
#    subscribe_cover = "img/logo.jpg"  # fallback: ""
#    subscribe_color = "#585e6c"       # fallback: ""
#    subscribe_size = "medium"         # options: small, medium, big
#    subscribe_format = "rectangle"    # options: rectangle, square, cover
#    subscribe_style = "filled"        # options: filled, outline, frameless
#    subscribe_language = "de"         # options: nl (dutch), en (english), eo (esperanto), de (german), fi (finnish), fr (french), ja (french)
#    subscribe_feed_type = "audio"     # options: audio, video
#    subscribe_feed_format = "mp3"     # options: mp3, aac, ogg, opus

  [params.social]
    github = "dacolloquium"
#    gitlab = ""
#    facebook = ""
#    facebook_admin = ["",""] # This needs to be one or more page admins to get domain insights
    twitter = "dacolloquium"
#    twitter_domain = "dacolloquium.com" # This domain shows in twitter cards as "View on `twitter_domain`"
#    googleplus = ""
#    pinterest = ""
#    instagram = ""
    youtube = "dacolloquium"
    linkedin = "dacolloquium"
#    twitch = ""
  [params.authors]
  [params.authors.1Peter]
			name = "Peter Pan"
			thumbnail = "img/host/chpan.jpg"
			bio = ""
  [params.authors.1Peter.social]
					twitter = "chpan"
  [params.authors.2Karl]
      name	= "Karl Ho"
      thumbnail = "img/host/KarlHo.jpg"
      bio = "Karl Ho is a political data scientist working at the intersection of data science and social science. His research interests span both domains of data analytics and political studies, with a regional focus on East Asia. The unifying theme of his research is to use fast growing data science methods, data-oriented research design and statistical computing to decipher and prescribe social and political problems. Areas of substantive topics include democratization, political economy, public policy and human rights. He pursues both data analytics and data modeling in building public goods, aiming at improving policies, governance and representation."
  [params.authors.2Karl.social]
        github = "karlho"
        facebook = "karlho"
        twitter = "karlho"
        linkedin = "karlho"
        homepage = "https://karlho.com"
        pinterest = ""
        instagram = ""
        youtube = ""
        twitch = ""
 
   # [params.links]
   #   [params.links.ado]
   #     name = "Arrested DevOps"
   #     url = "https://www.arresteddevops.com"
   #   [params.links.ffs]
   #     name = "Food Fight Show"
   #     url = "https://foodfightshow.org"
   #   [params.links.sdt]
   #     name = "Software Defined Talk"
   #     url = "https://cote.io/podcasts/sdt/"
